[build]
  command = "cd my-architecture-site && npm run build"
  publish = "my-architecture-site/dist"
  base = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200